"use client";
import {useEffect,useMemo,useRef,useState} from "react";
type P={product_id:string;canonical_name:string;set_name:string|null;card_number:string|null;rarity:string|null;variant_key:string;variant_base_name:string;cd_latest_price_jpy:number|null;cd_latest_observed_at:string|null;ha_latest_price_jpy:number|null;ha_latest_observed_at:string|null;best_exit_price_jpy:number|null};
type H={product_id:string;source_name:string;observed_day:string;price_jpy:number;observed_at:string;variant_key?:string;variant_base_name?:string};
const yen=(n:number|null|undefined)=>n==null?"—":"¥"+Math.round(n).toLocaleString("ja-JP");
const variantLabel=(k:string|undefined)=>{
  if(!k||k==="NORMAL") return "通常仕様";
  return k.split("+").map(x=>x==="MASTERBALL_MIRROR"?"マスターボールミラー":x==="MONSTERBALL_MIRROR"?"モンスターボールミラー":x==="MIRROR"?"ミラー":x==="UNOPENED"?"未開封":x).join(" + ");
};
const dt=(s:string)=>new Date(s).toLocaleString("ja-JP",{year:"numeric",month:"2-digit",day:"2-digit",hour:"2-digit",minute:"2-digit"});
const latestKnown=(rows:H[],productId:string,source:string)=>{const rs=rows.filter(r=>r.product_id===productId&&r.source_name===source).sort((a,b)=>a.observed_at.localeCompare(b.observed_at));return rs.length?rs[rs.length-1]:null;};
const weekChange=(rows:H[],source:string)=>{const rs=rows.filter(r=>r.source_name===source).sort((a,b)=>a.observed_at.localeCompare(b.observed_at));if(rs.length<2)return null;const latest=rs[rs.length-1],cut=new Date(new Date(latest.observed_at).getTime()-7*86400000);let base=rs[0];for(const r of rs){if(new Date(r.observed_at)<=cut)base=r;else break}if(base.price_jpy===0)return null;return {pct:(latest.price_jpy-base.price_jpy)/base.price_jpy*100,base,latest};};
function Chart({rows}:{rows:H[]}){const ds=[...new Set(rows.map(r=>r.observed_day))].sort(),by=(s:string)=>rows.filter(r=>r.source_name===s).sort((a,b)=>a.observed_at.localeCompare(b.observed_at)),vals=rows.map(r=>r.price_jpy),min=Math.min(...vals),max=Math.max(...vals),range=Math.max(1,max-min),w=760,h=300,p=54,x=(i:number)=>p+(ds.length<=1?0:i*(w-p*2)/(ds.length-1)),y=(v:number)=>h-p-(v-min)*(h-p*2)/range,delta=(rs:H[],i:number)=>i>0?rs[i].price_jpy-rs[i-1].price_jpy:null,fmtDelta=(n:number)=> (n>=0?"+":"")+"¥"+Math.abs(Math.round(n)).toLocaleString("ja-JP"),fmtPrice=(n:number)=>"¥"+Math.round(n).toLocaleString("ja-JP"),ticks=5,step=range/ticks;return <div className="chart-wrap"><div className="chart-legend"><span>● CD</span><span>● HA</span><span className="chart-legend-note">データラベル＝価格金額 ／ 点をホバーすると前回比金額・取得時刻を表示</span></div><svg viewBox={"0 0 "+w+" "+h} className="chart">{Array.from({length:ticks+1},(_,i)=>{const v=min+step*i;return <g key={"tick-"+i}><line x1={p} x2={w-p} y1={y(v)} y2={y(v)} stroke="#202832" strokeDasharray="2 3"/><text x={p-7} y={y(v)+3} textAnchor="end" className="axis">{fmtPrice(v)}</text></g>})}<line x1={p} x2={w-p} y1={h-p} y2={h-p} stroke="#29313c"/>{(["CD","HA"] as const).map((s,si)=>{const rs=by(s);return <g key={s}><polyline points={rs.map(r=>x(ds.indexOf(r.observed_day))+","+y(r.price_jpy)).join(" ")} fill="none" stroke={si===0?"#73e8a2":"#8b9bad"} strokeWidth="3"/>{rs.map((r,i)=>{const d=delta(rs,i),last=i===rs.length-1,showDelta=d!==null&&d!==0;return <g key={s+"-"+r.observed_at+"-"+i}><circle cx={x(ds.indexOf(r.observed_day))} cy={y(r.price_jpy)} r={4} fill={si===0?"#73e8a2":"#8b9bad"}><title>{s+" · "+r.observed_day+" · 価格 "+yen(r.price_jpy)+(d===null?"":" · 前回比 "+fmtDelta(d))+" · 取得 "+dt(r.observed_at)}</title></circle><text x={x(ds.indexOf(r.observed_day))} y={Math.max(14,y(r.price_jpy)-9)} textAnchor="middle" className="chart-price-label">{fmtPrice(r.price_jpy)}</text>{showDelta&&<text x={x(ds.indexOf(r.observed_day))} y={Math.min(h-p-4,y(r.price_jpy)+15)} textAnchor="middle" className={d>=0?"chart-delta chart-delta-up":"chart-delta chart-delta-down"}>{fmtDelta(d)}</text>}</g>})}</g>})}<text x={p} y={h-7} className="axis">{ds[0]}</text><text x={w-p} y={h-7} textAnchor="end" className="axis">{ds[ds.length-1]}</text></svg></div>}

export default function Search(){const[name,setName]=useState(""),[num,setNum]=useState(""),[game,setGame]=useState(new URLSearchParams(location.search).get("game")||"pokemon"),[d,setD]=useState<any>(null),[busy,setBusy]=useState(false),[selected,setSelected]=useState<string|null>(null),detailRef=useRef<HTMLElement|null>(null);
const selectProduct=(id:string)=>{setSelected(id);setTimeout(()=>detailRef.current?.scrollIntoView({behavior:"smooth",block:"start"}),50)};
async function load(n=name,k=num,pid="",g=game){setBusy(true);const q=new URLSearchParams();q.set("game",g);if(pid)q.set("product_id",pid);else{if(n.trim())q.set("card_name",n.trim());if(k.trim())q.set("card_number",k.trim())}q.set("history","1");q.set("days","90");q.set("limit","100");try{const r=await fetch("/api/radar?"+q,{cache:"no-store"});setD(await r.json());setSelected(pid||null)}finally{setBusy(false)}}
useEffect(()=>{const u=new URLSearchParams(location.search);const g=u.get("game")||"pokemon";setGame(g);const pid=u.get("product_id");if(pid)load("","",pid,g)},[]);
const prices:P[]=d?.prices??[],history:H[]=d?.history??[],latestObserved=(field:"cd_latest_observed_at"|"ha_latest_observed_at")=>{const rs=prices.map(p=>p[field]).filter((v):v is string=>!!v);return rs.length?rs.reduce((a,b)=>a>b?a:b):null},selectedPrice=prices.find(p=>p.product_id===selected),selectedHistory=history.filter(h=>h.product_id===selected),latest=useMemo(()=>{const m=new Map<string,H>();selectedHistory.forEach(r=>{const o=m.get(r.source_name);if(!o||r.observed_at>o.observed_at)m.set(r.source_name,r)});return m},[selectedHistory]);
const cd7=selectedHistory.length?weekChange(selectedHistory,"CD"):null,ha7=selectedHistory.length?weekChange(selectedHistory,"HA"):null;
return <main><header><div className="brand"><span>⚡</span><div><b>Cross-Border Seller Radar</b><small>SEARCH · CD / HA BUYBACK</small></div></div><a className="back" href="/">← ランキングへ</a></header>
<section className="search-hero"><small>CARD SEARCH</small><h1>カードを探す。</h1><p>カード名または型番を入力すると、CD / HA の買取価格をすぐ比較できます。</p><div style={{display:"flex",gap:8,flexWrap:"wrap",marginBottom:12}}>{[["pokemon","Pokemon"],["one_piece","ONE PIECE"],["yugioh","Yu-Gi-Oh!"],["mtg","Magic: The Gathering"]].map(([code,label])=><button type="button" key={code} onClick={()=>{setGame(code);const u=new URLSearchParams(location.search);u.set("game",code);history.replaceState(null,"","?"+u.toString());load(name,num,"",code)}} style={{opacity:game===code?1:.55,fontWeight:game===code?800:600}}>{label}</button>)}</div><section className="search search-primary"><input autoFocus value={name} onChange={e=>setName(e.target.value)} onKeyDown={e=>e.key==="Enter"&&load()} placeholder="カード名（例：ミロカロスex）"/><input value={num} onChange={e=>setNum(e.target.value)} onKeyDown={e=>e.key==="Enter"&&load()} placeholder="型番（例：131/106）"/><button onClick={()=>load()}>検索</button></section></section>
{busy&&<div className="empty">検索しています…</div>}
{!busy&&prices.length>0&&<section className="search-results"><div className="head"><div><small>RESULTS</small><h2>{prices.length.toLocaleString()}件の検索結果</h2><div className="result-freshness"><span>CD 最新取得 {latestObserved("cd_latest_observed_at")?dt(latestObserved("cd_latest_observed_at")!):"—"}</span><span>HA 最新取得 {latestObserved("ha_latest_observed_at")?dt(latestObserved("ha_latest_observed_at")!):"—"}</span></div></div></div><div className="mobile-results mobile-price-table-wrap"><table className="mobile-price-table"><thead><tr><th>カード</th><th>CD買取</th><th>HA買取</th></tr></thead><tbody>{prices.map(p=>{const cdKnown=latestKnown(history,p.product_id,"CD"),haKnown=latestKnown(history,p.product_id,"HA");return <tr key={p.product_id} onClick={()=>selectProduct(p.product_id)}><td><strong>{p.canonical_name}</strong><small>{variantLabel(p.variant_key)} · {p.card_number??"—"} · {p.set_name??"—"}</small></td><td><b>{yen(p.cd_latest_price_jpy)}</b><small>{p.cd_latest_observed_at?dt(p.cd_latest_observed_at):cdKnown?`最終取得 ${dt(cdKnown.observed_at)}`:"—"}</small></td><td><b>{yen(p.ha_latest_price_jpy)}</b><small>{p.ha_latest_observed_at?dt(p.ha_latest_observed_at):haKnown?`最終取得 ${dt(haKnown.observed_at)}`:"—"}</small></td></tr>})}</tbody></table></div><div className="table-wrap desktop-results"><div className="result-row result-head"><span>カード名</span><span>パック</span><span>レアリティ</span><span>型番</span><span>CD</span><span>HA</span></div>{prices.map(p=>{const cdKnown=latestKnown(history,p.product_id,"CD"),haKnown=latestKnown(history,p.product_id,"HA");return <button type="button" className={"result-row result-button"+(selected===p.product_id?" selected":"")} key={p.product_id} onClick={()=>selectProduct(p.product_id)}><strong>{p.canonical_name}<small className="variant-inline">{variantLabel(p.variant_key)}</small></strong><span>{p.set_name??"—"}</span><span>{p.rarity??"—"}</span><span className="mono">{p.card_number??"—"}</span><span className="buy-cell" aria-label={`CD買取 ${yen(p.cd_latest_price_jpy)}`}><strong className="buy-label">CD買取</strong><b>{yen(p.cd_latest_price_jpy)}</b><small>{p.cd_latest_observed_at?dt(p.cd_latest_observed_at):"現行データ未取得"}</small></span><span className="buy-cell" aria-label={`HA買取 ${yen(p.ha_latest_price_jpy)}`}><strong className="buy-label">HA買取</strong><b>{yen(p.ha_latest_price_jpy)}</b><small>{p.ha_latest_observed_at?dt(p.ha_latest_observed_at):"現行データ未取得"}</small></span></button>})}</div></section>}
{!busy&&!prices.length&&d&&<div className="empty">一致するCD / HA価格データがありません。</div>}
{selectedPrice&&<section ref={detailRef} className="detail search-detail"><button className="back" onClick={()=>setSelected(null)}>← 検索結果へ戻る</button><div className="detail-title"><div><small>PRICE HISTORY · 90 DAYS</small><h2>{selectedPrice.canonical_name}</h2><p>{variantLabel(selectedPrice.variant_key)} · {selectedPrice.set_name??"—"} · {selectedPrice.card_number??"—"} · {selectedPrice.rarity??"—"}</p></div><div className="detail-buy-pair"><div><span>CD買取</span><b>{yen(selectedPrice.cd_latest_price_jpy)}</b><small>{selectedPrice.cd_latest_observed_at?`取得: ${dt(selectedPrice.cd_latest_observed_at)}`:"現行データ未取得"}</small><em className={(cd7?.pct??0)>=0?"profit":"loss"}>7日 {cd7==null?"—":((cd7.pct>=0?"+":"")+cd7.pct.toFixed(1)+"%")}</em></div><div><span>HA買取</span><b>{yen(selectedPrice.ha_latest_price_jpy)}</b><small>{selectedPrice.ha_latest_observed_at?`取得: ${dt(selectedPrice.ha_latest_observed_at)}`:"現行データ未取得"}</small><em className={(ha7?.pct??0)>=0?"profit":"loss"}>7日 {ha7==null?"—":((ha7.pct>=0?"+":"")+ha7.pct.toFixed(1)+"%")}</em></div></div></div>{selectedHistory.length?<Chart rows={selectedHistory}/>:<div className="empty">履歴データがありません。</div>}</section>}
<footer>Cross-Border Seller Radar · Search-first mobile UI</footer></main>}