"use client";
import {useEffect,useMemo,useState} from "react";
type P={product_id:string;canonical_name:string;set_name:string|null;card_number:string|null;rarity:string|null;cardrush_latest_price_jpy:number|null;hareruya_latest_price_jpy:number|null;best_exit_price_jpy:number|null};
type H={product_id:string;source_name:string;observed_day:string;price_jpy:number;observed_at:string};
const yen=(n:number|null|undefined)=>n==null?"—":"¥"+Math.round(n).toLocaleString("ja-JP");
function Chart({rows}:{rows:H[]}){const ds=[...new Set(rows.map(r=>r.observed_day))].sort(),by=(s:string)=>rows.filter(r=>r.source_name===s).sort((a,b)=>a.observed_day.localeCompare(b.observed_day)),vals=rows.map(r=>r.price_jpy),min=Math.min(...vals),max=Math.max(...vals),range=Math.max(1,max-min),w=760,h=240,p=28,x=(i:number)=>p+(ds.length<=1?0:i*(w-p*2)/(ds.length-1)),y=(v:number)=>h-p-(v-min)*(h-p*2)/range;return <div className="chart-wrap"><div className="chart-legend"><span>● CD</span><span>● HA</span></div><svg viewBox={`0 0 ${w} ${h}`} className="chart"><line x1={p} x2={w-p} y1={h-p} y2={h-p} stroke="#29313c"/>{(["CD","HA"] as const).map((s,si)=>{const rs=by(s);return <polyline key={s} points={rs.map(r=>`${x(ds.indexOf(r.observed_day))},${y(r.price_jpy)}`).join(" ")} fill="none" stroke={si===0?"#73e8a2":"#8b9bad"} strokeWidth="3"/>})}<text x={p} y={h-7} className="axis">{ds[0]}</text><text x={w-p} y={h-7} textAnchor="end" className="axis">{ds[ds.length-1]}</text></svg></div>}
export default function Search(){const[name,setName]=useState(""),[num,setNum]=useState(""),[d,setD]=useState<any>(null),[busy,setBusy]=useState(false),[selected,setSelected]=useState<string|null>(null);
async function load(n=name,k=num,pid=""){setBusy(true);const q=new URLSearchParams();if(pid)q.set("product_id",pid);else{if(n.trim())q.set("card_name",n.trim());if(k.trim())q.set("card_number",k.trim())}q.set("history","1");q.set("days","90");q.set("limit","100");try{const r=await fetch("/api/radar?"+q,{cache:"no-store"});setD(await r.json());setSelected(pid||null)}finally{setBusy(false)}}
useEffect(()=>{const q=new URLSearchParams(location.search);load("","",q.get("product_id")||"")},[]);
const prices:P[]=d?.prices??[],history:H[]=d?.history??[],selectedPrice=prices.find(p=>p.product_id===selected),selectedHistory=history.filter(h=>h.product_id===selected),latest=useMemo(()=>{const m=new Map<string,H>();selectedHistory.forEach(r=>{const o=m.get(r.source_name);if(!o||r.observed_at>o.observed_at)m.set(r.source_name,r)});return m},[selectedHistory]);
return <main><header><div className="brand"><span>⚡</span><div><b>Cross-Border Seller Radar</b><small>SEARCH · CD / HA BUYBACK</small></div></div><a className="back" href="/">← ランキングへ</a></header>
<section className="search-hero"><small>CARD SEARCH</small><h1>カードを探す。</h1><p>カード名または型番を入力すると、CD / HA の買取価格をすぐ比較できます。</p><section className="search search-primary"><input autoFocus value={name} onChange={e=>setName(e.target.value)} onKeyDown={e=>e.key==="Enter"&&load()} placeholder="カード名（例：ミロカロスex）"/><input value={num} onChange={e=>setNum(e.target.value)} onKeyDown={e=>e.key==="Enter"&&load()} placeholder="型番（例：131/106）"/><button onClick={()=>load()}>検索</button></section></section>
{busy&&<div className="empty">検索しています…</div>}
{!busy&&prices.length>0&&<section className="search-results"><div className="head"><div><small>RESULTS</small><h2>{prices.length.toLocaleString()}件の検索結果</h2></div></div><div className="mobile-results">{prices.map(p=><button className="mobile-result-card" key={p.product_id} onClick={()=>setSelected(p.product_id)}><div className="mobile-card-title"><strong>{p.canonical_name}</strong><span>{p.card_number??"—"}</span></div><small>{p.set_name??"—"} · {p.rarity??"—"}</small><div className="mobile-buy-grid"><div><i>CD</i><b>{yen(p.cardrush_latest_price_jpy)}</b></div><div><i>HA</i><b>{yen(p.hareruya_latest_price_jpy)}</b></div></div></button>)}</div><div className="table-wrap desktop-results"><div className="result-row result-head"><span>カード名</span><span>パック</span><span>レアリティ</span><span>型番</span><span>CD</span><span>HA</span></div>{prices.map(p=><button type="button" className={"result-row result-button"+(selected===p.product_id?" selected":"")} key={p.product_id} onClick={()=>setSelected(p.product_id)}><strong>{p.canonical_name}</strong><span>{p.set_name??"—"}</span><span>{p.rarity??"—"}</span><span className="mono">{p.card_number??"—"}</span><span className="buy-cell"><b>{yen(p.cardrush_latest_price_jpy)}</b></span><span className="buy-cell"><b>{yen(p.hareruya_latest_price_jpy)}</b></span></button>)}</div></section>}
{!busy&&!prices.length&&d&&<div className="empty">一致するCD / HA価格データがありません。</div>}
{selectedPrice&&<section className="detail search-detail"><button className="back" onClick={()=>setSelected(null)}>← 検索結果へ戻る</button><div className="detail-title"><div><small>PRICE HISTORY · 90 DAYS</small><h2>{selectedPrice.canonical_name}</h2><p>{selectedPrice.set_name??"—"} · {selectedPrice.card_number??"—"} · {selectedPrice.rarity??"—"}</p></div><div className="detail-buy-pair"><div><span>CD</span><b>{yen(latest.get("CD")?.price_jpy??selectedPrice.cardrush_latest_price_jpy)}</b></div><div><span>HA</span><b>{yen(latest.get("HA")?.price_jpy??selectedPrice.hareruya_latest_price_jpy)}</b></div></div></div>{selectedHistory.length?<Chart rows={selectedHistory}/>:<div className="empty">履歴データがありません。</div>}</section>}
<footer>Cross-Border Seller Radar · Search-first mobile UI</footer></main>}