"use client";
import {useEffect,useState} from "react";
type C={rank:number;product_id:string;canonical_name:string;set_name:string|null;card_number:string|null;current_price_jpy:number;previous_price_jpy:number;change_jpy:number;change_percent:number;current_observed_at:string;previous_observed_at:string};
type S={rank:number;product_id:string;canonical_name:string;set_name:string|null;card_number:string|null;cd_price_jpy:number;ha_price_jpy:number;difference_jpy:number;difference_percent:number;cd_observed_at:string;ha_observed_at:string};
const yen=(n:number)=>"¥"+Math.round(n).toLocaleString("ja-JP"),pct=(n:number)=>(n>=0?"+":"")+n.toFixed(1)+"%",dt=(s:string)=>new Date(s).toLocaleString("ja-JP",{year:"numeric",month:"2-digit",day:"2-digit",hour:"2-digit",minute:"2-digit"});
export default function Home(){const[d,setD]=useState<{change_rankings:{CD:C[];HA:C[]};spread_rankings:{CD:S[];HA:S[]}}>({change_rankings:{CD:[],HA:[]},spread_rankings:{CD:[],HA:[]}});useEffect(()=>{fetch("/api/radar?all_changes=1&all_spreads=1",{cache:"no-store"}).then(r=>r.json()).then(x=>setD({change_rankings:x.change_rankings??{CD:[],HA:[]},spread_rankings:x.spread_rankings??{CD:[],HA:[]}})).catch(()=>{})},[]);
return <main><header><div className="brand"><span>⚡</span><div><b>Cross-Border Seller Radar</b><small>AKIHABARA · BUYBACK INTELLIGENCE</small></div></div><span className="live">● LIVE</span></header>
<section className="ranking-hero"><small>MARKET RADAR</small><h1>買取価格の変動と、<br/><em>CD / HA の価格差。</em></h1><p>ランキング専用ページです。カードを探すときは検索ページから、カード名・型番で直接検索できます。</p><a className="primary-link" href="/search">🔎 カードを検索する →</a></section>
<section className="ranking-section"><div className="head"><div><small>PRICE CHANGE</small><h2>前回比 変動ランキング</h2></div><a className="all-changes-link" href="/changes">全件を見る →</a></div><div className="ranking-grid">{(["CD","HA"] as const).map(ch=><div className="ranking-card" key={ch}><div className="ranking-card-head"><b>{ch}</b><span>変動率の大きい順</span></div>{d.change_rankings[ch].slice(0,50).map(r=><a className="ranking-row" key={r.product_id} href={"/search?product_id="+encodeURIComponent(r.product_id)}><span className="rank-no">{r.rank}</span><span className="rank-name"><strong>{r.canonical_name}</strong><small>{r.set_name??"—"} · <b className="rank-card-number">{r.card_number??"—"}</b></small></span><span className="rank-prices"><span className="rank-price-line"><b>{yen(r.previous_price_jpy)}</b><span>→</span><b>{yen(r.current_price_jpy)}</b></span><span className="rank-change"><b className={r.change_jpy>=0?"profit":"loss"}>{r.change_jpy>=0?"+":""}{yen(Math.abs(r.change_jpy))}</b><b className={r.change_percent>=0?"profit":"loss"}>{pct(r.change_percent)}</b></span><em>{dt(r.previous_observed_at)} → {dt(r.current_observed_at)}</em></span></a>)}</div>)}</div></section>
<section className="ranking-section"><div className="head"><div><small>BUYBACK SPREAD</small><h2>CD / HA 買取価格差ランキング</h2></div><a className="all-changes-link" href="/spreads">全件を見る →</a></div><div className="ranking-grid">{(["HA","CD"] as const).map(ch=><div className="ranking-card" key={ch}><div className="ranking-card-head"><b>{ch} が高い</b><span>価格差の大きい順</span></div>{d.spread_rankings[ch].slice(0,50).map(r=><a className="spread-row" key={r.product_id} href={"/search?product_id="+encodeURIComponent(r.product_id)}><span className="rank-no">{r.rank}</span><span className="rank-name"><strong>{r.canonical_name}</strong><small>{r.set_name??"—"} · <b className="rank-card-number">{r.card_number??"—"}</b></small></span><span className="spread-prices"><span><i>CD</i> {yen(r.cd_price_jpy)}</span><span><i>HA</i> {yen(r.ha_price_jpy)}</span><b className="profit">+{yen(Math.abs(r.difference_jpy))}</b><em>{r.difference_percent.toFixed(1)}%</em></span></a>)}</div>)}</div></section>
<footer>Cross-Border Seller Radar · CD / HA separated comparison</footer></main>}