"use client";
import {useEffect,useMemo,useRef,useState} from "react";

type Price={product_id:string;canonical_name:string;set_name:string|null;card_number:string|null;rarity:string|null;cardrush_buy_price_jpy:number|null;cardrush_latest_price_jpy:number|null;cardrush_latest_observed_at:string|null;hareruya_latest_price_jpy:number|null;hareruya_latest_observed_at:string|null;best_exit_price_jpy:number|null;best_exit_source_name:string|null;cross_source_spread_jpy:number|null;cross_source_spread_percent:string|null};
type HistoryRow={product_id:string;canonical_name:string;set_name:string|null;card_number:string|null;rarity:string|null;source_id:string;source_name:string;observed_day:string;price_jpy:number;observed_at:string};
type ChangeRow={rank:number;product_id:string;canonical_name:string;set_name:string|null;card_number:string|null;rarity:string|null;current_price_jpy:number;previous_price_jpy:number;change_jpy:number;change_percent:number;current_observed_at:string;previous_observed_at:string};
type SpreadRow={rank:number;product_id:string;canonical_name:string;set_name:string|null;card_number:string|null;rarity:string|null;cd_price_jpy:number;ha_price_jpy:number;difference_jpy:number;difference_percent:number;cd_observed_at:string;ha_observed_at:string};
const yen=(n:number|null|undefined)=>n==null?"—":"¥"+Math.round(n).toLocaleString("ja-JP");
const pct=(n:number|null|undefined)=>n==null?"—":(n>=0?"+":"")+n.toFixed(1)+"%";
const daysAgo=(iso:string,d:number)=>new Date(iso).getTime()>=Date.now()-d*86400000;

function HistoryChart({rows}:{rows:HistoryRow[]}){
 const bySource=useMemo(()=>{const m=new Map<string,HistoryRow[]>();rows.filter(r=>r.source_name==="CardRush"||r.source_name==="晴れる屋2").forEach(r=>{const name=r.source_name==="CardRush"?"CD":"HA";if(!m.has(name))m.set(name,[]);m.get(name)!.push(r)});return [...m.entries()].map(([name,rs])=>[name,[...rs].sort((a,b)=>a.observed_day.localeCompare(b.observed_day))] as const)},[rows]);
 const dates=[...new Set(rows.map(r=>r.observed_day))].sort(); if(!rows.length)return <div className="empty">このカードの履歴データはまだ十分にありません。</div>;
 const values=rows.map(r=>r.price_jpy),min=Math.min(...values),max=Math.max(...values),range=Math.max(1,max-min),w=760,h=230,pad=28;
 const x=(i:number)=>pad+(dates.length<=1?0:i*(w-pad*2)/(dates.length-1)),y=(v:number)=>h-pad-(v-min)*(h-pad*2)/range;
 return <div className="chart-wrap"><div className="chart-legend">{bySource.map(([name])=><span key={name}>● {name}</span>)}</div><svg viewBox={`0 0 ${w} ${h}`} className="chart" role="img" aria-label="価格推移"><line x1={pad} x2={w-pad} y1={h-pad} y2={h-pad} stroke="#29313c"/><line x1={pad} x2={pad} y1={pad} y2={h-pad} stroke="#29313c"/>{[0,.5,1].map(t=><text key={t} x="2" y={pad+(h-pad*2)*t+4} className="axis">{yen(max-(max-min)*t)}</text>)}{bySource.map(([name,rs],si)=>{const pts=rs.map(r=>{const i=dates.indexOf(r.observed_day);return `${x(i)},${y(r.price_jpy)}`}).join(" ");return <polyline key={name} points={pts} fill="none" stroke={si===0?"#73e8a2":"#8b9bad"} strokeWidth="3" strokeLinejoin="round" strokeLinecap="round"/>})}{dates.length>0&&<><text x={pad} y={h-6} className="axis">{dates[0]}</text><text x={w-pad} y={h-6} textAnchor="end" className="axis">{dates[dates.length-1]}</text></>}</svg></div>;
}

export default function Home(){
 const[data,setData]=useState<any>(null),[cardName,setCardName]=useState(""),[cardNumber,setCardNumber]=useState(""),[busy,setBusy]=useState(true),[tab,setTab]=useState<"radar"|"calc">("radar"),[selected,setSelected]=useState<string|null>(null);
 const detailRef=useRef<HTMLElement|null>(null);
 async function load(name="",number="",withHistory=false,productId=""){setBusy(true);try{const params=new URLSearchParams();if(productId)params.set("product_id",productId);else {if(name.trim())params.set("card_name",name.trim());if(number.trim())params.set("card_number",number.trim())}if(withHistory){params.set("history","1");params.set("days","90");params.set("limit","100")}const r=await fetch("/api/radar"+(params.size?"?"+params:""),{cache:"no-store"});setData(await r.json());if(productId)setSelected(productId);else setSelected(null)}catch{}finally{setBusy(false)}}
 useEffect(()=>{const pid=new URLSearchParams(window.location.search).get("product_id");if(pid)load("","",true,pid);else load()},[]);
 useEffect(()=>{if(selected&&detailRef.current)requestAnimationFrame(()=>detailRef.current?.scrollIntoView({behavior:"smooth",block:"start"}))},[selected]);
 const prices:Price[]=data?.prices??[],sources=data?.sources??[],history:HistoryRow[]=data?.history??[],changeRankings=(data?.change_rankings??{CD:[],HA:[]}) as {CD:ChangeRow[];HA:ChangeRow[]},hasSearch=!!(cardName.trim()||cardNumber.trim());
 const live=sources.filter((s:any)=>s.enabled&&s.latest_product_count>0&&(s.name==="CardRush"||s.name==="晴れる屋2")),positive=prices.filter(p=>(p.cross_source_spread_jpy??0)>0).length,searchCount=(data?.search??[]).length;
 const summary=useMemo(()=>{const exits=prices.map(p=>p.best_exit_price_jpy??p.cardrush_buy_price_jpy).filter(Boolean) as number[];return exits.length?Math.round(exits.reduce((a,b)=>a+b,0)/exits.length):0},[prices]);
 const selectedPrice=prices.find(p=>p.product_id===selected)??null;
 const selectedHistory=selected?history.filter(h=>h.product_id===selected&&(h.source_name.includes("CardRush")||h.source_name.includes("晴れる屋2"))):[];
 const stats=useMemo(()=>{if(!selectedHistory.length)return null;const latestBySource=new Map<string,HistoryRow>();selectedHistory.forEach(r=>{const old=latestBySource.get(r.source_name);if(!old||r.observed_at>old.observed_at)latestBySource.set(r.source_name,r)});const all=[...latestBySource.values()],latest=all.length?Math.max(...all.map(r=>r.price_jpy)):null;const first=(d:number)=>{const rs=selectedHistory.filter(r=>daysAgo(r.observed_at,d));if(!rs.length)return null;const earliest=[...rs].sort((a,b)=>a.observed_at.localeCompare(b.observed_at))[0];return latest&&earliest.price_jpy?((latest-earliest.price_jpy)/earliest.price_jpy)*100:null};const values=selectedHistory.map(r=>r.price_jpy);return{latest,max:Math.max(...values),min:Math.min(...values),c7:first(7),c30:first(30),sources:all}},[selectedHistory]);

 return <main>
 <header><div className="brand"><span>⚡</span><div><b>Cross-Border Seller Radar</b><small>AKIHABARA · LIVE BUYBACK INTELLIGENCE</small></div></div><span className="live">● LIVE</span></header>
 <section className="hero"><div><small>RAW CARD → BEST EXIT</small><h1>店頭で見つけた瞬間に、<br/><em>売り先まで判断する。</em></h1><p>複数の買取データを横断し、カードを見つけたその場で出口価格と仕入れ採算を確認するためのレーダーです。</p><div className="hero-stats"><span><b>{live.length}</b> LIVE SOURCES</span><span><b>{prices.length.toLocaleString()}</b> COMPARISONS</span><span><b>{positive}</b> POSITIVE SPREADS</span></div></div><aside><small>平均 BEST EXIT</small><strong>{yen(summary)}</strong><label>現在表示中の価格</label></aside></section>
 <div style={{maxWidth:1106,margin:"0 auto",padding:"0 22px 18px"}}><a href="/scan" style={{color:"#73e8a2",fontSize:11,fontWeight:800}}>📹 店頭動画をスキャンする →</a></div>
 <nav className="tabs"><button className={tab==="radar"?"active":""} onClick={()=>setTab("radar")}>価格レーダー</button><button className={tab==="calc"?"active":""} onClick={()=>setTab("calc")}>仕入れ判定</button></nav>
 {tab==="radar"?<>
 <section className="search"><input value={cardName} onChange={e=>setCardName(e.target.value)} onKeyDown={e=>e.key==="Enter"&&load(cardName,cardNumber,true)} placeholder="カード名（例：ピカチュウ）"/><input value={cardNumber} onChange={e=>setCardNumber(e.target.value)} onKeyDown={e=>e.key==="Enter"&&load(cardName,cardNumber,true)} placeholder="型番（例：205/187）"/><button onClick={()=>load(cardName,cardNumber,true)}>検索</button></section>
 {hasSearch&&<div className="hint">{searchCount}件のカード候補 · 行をクリックすると価格推移へ移動</div>}{!hasSearch&&<section className="change-ranking">
   <div className="head"><div><small>PRICE CHANGE</small><h2>前回比 変動ランキング</h2></div><div className="ranking-actions"><span className="ranking-note">0%変動は除外 · 同一買取先内で比較</span><a className="all-changes-link" href="/changes">変動ランキングをすべて見る →</a></div></div>
   <div className="ranking-grid">{(["CD","HA"] as const).map(channel=><div className="ranking-card" key={channel}>
     <div className="ranking-card-head"><b>{channel}</b><span>前回 → 現在</span></div>
     {changeRankings[channel].length?changeRankings[channel].map((r,i)=><button type="button" className="ranking-row" key={r.product_id} onClick={()=>{setCardName(r.canonical_name);setCardNumber(r.card_number??"");load(r.canonical_name,r.card_number??"",true,r.product_id)}}><span className="rank-no">{i+1}</span><span className="rank-name"><strong>{r.canonical_name}</strong><small>{r.set_name??"—"} · {r.card_number??"—"}</small></span><span className="rank-prices"><span className="rank-price-line"><b>{yen(r.previous_price_jpy)}</b><span>→</span><b>{yen(r.current_price_jpy)}</b></span><span className="rank-change"><b className={r.change_jpy>=0?"profit":"loss"}>{r.change_jpy>=0?"+":""}{yen(Math.abs(r.change_jpy))}</b><b className={r.change_percent>=0?"profit":"loss"}>{pct(r.change_percent)}</b></span><em>{new Date(r.previous_observed_at).toLocaleString("ja-JP")} → {new Date(r.current_observed_at).toLocaleString("ja-JP")}</em></span></button>):<div className="ranking-empty">まだ前回値と比較できる変動データがありません。</div>}
   </div>)}</div>
 </section>}
 {selectedPrice&&<section className="detail" ref={detailRef}>
   <button className="back" onClick={()=>setSelected(null)}>← 検索結果へ戻る</button>
   <div className="detail-title"><div><small>PRICE HISTORY · 90 DAYS</small><h2>{selectedPrice.canonical_name}</h2><p>{selectedPrice.set_name??"その他"} · {selectedPrice.card_number??"—"} · {selectedPrice.rarity??"—"}</p></div><div className="detail-current"><span>BEST EXIT</span><b>{yen(selectedPrice.best_exit_price_jpy??selectedPrice.cardrush_buy_price_jpy)}</b></div></div>
   {stats&&<div className="stat-grid"><div><span>7日変化</span><b className={(stats.c7??0)>=0?"profit":"loss"}>{pct(stats.c7)}</b></div><div><span>30日変化</span><b className={(stats.c30??0)>=0?"profit":"loss"}>{pct(stats.c30)}</b></div><div><span>90日最高</span><b>{yen(stats.max)}</b></div><div><span>90日最低</span><b>{yen(stats.min)}</b></div></div>}
   <HistoryChart rows={selectedHistory}/>
 </section>}
 <section className="head"><div><small>MARKET EXIT</small><h2>{hasSearch?"検索結果":"現在の買取レーダー"}</h2></div><button className="ghost" onClick={()=>load(cardName,cardNumber,hasSearch)}>↻ 更新</button></section>
 <section className="result-list">{busy?<div className="empty">価格データを読み込んでいます…</div>:prices.length?<div className="table-wrap"><div className="result-row result-head"><span>カード名</span><span>パック</span><span>レアリティ</span><span>型番</span><span>CD</span><span>HA</span></div>{prices.map(p=><button type="button" key={p.product_id} className={"result-row result-button"+(selected===p.product_id?" selected":"")} onClick={()=>setSelected(p.product_id)}><strong>{p.canonical_name}</strong><span>{p.set_name??"—"}</span><span>{p.rarity??"—"}</span><span className="mono">{p.card_number??"—"}</span><span className="buy-cell"><b>{yen(p.cardrush_latest_price_jpy??p.cardrush_buy_price_jpy)}</b></span><span className="buy-cell"><b>{yen(p.hareruya_latest_price_jpy)}</b></span></button>)}</div>:<div className="empty">一致する価格データがありません。</div>}</section>
 </>:<section className="calculator"><small>FAST DECISION</small><h2>仕入れ判定</h2><p>店頭価格と出口価格を入力して、交通費などを含めた簡易ROIを計算できます。</p><label>仕入れ価格<input id="buy" inputMode="numeric" placeholder="12000"/></label><label>出口価格<input id="exit" inputMode="numeric" placeholder="18000"/></label><label>その他コスト<input id="other" inputMode="numeric" placeholder="500"/></label><button onClick={()=>{const b=Number((document.getElementById("buy") as HTMLInputElement).value||0),e=Number((document.getElementById("exit") as HTMLInputElement).value||0),o=Number((document.getElementById("other") as HTMLInputElement).value||0),p=e-b-o,r=b?p/b*100:0;const el=document.getElementById("result");if(el)el.textContent=b?((p>=0?"+":"")+yen(p)+" · ROI "+r.toFixed(1)+"%"):"仕入れ価格を入力してください"}}>計算する</button><div id="result" className="result">仕入れ価格を入力してください</div><small className="notice">※ 実際の買取額はカード状態、在庫、買取制限、店舗条件、交通費等で変動します。画面のROIは入力値による試算です。</small></section>}
  <footer>Cross-Border Seller Radar · Supabase × Vercel</footer>
 </main>
}